/*
	adSubArrayOfUsermanager_Datastructure_Role.h
	The implementation of properties and methods for the adSubArrayOfUsermanager_Datastructure_Role object.
	Generated by SudzC.com
*/
#import "adSubArrayOfUsermanager_Datastructure_Role.h"

@implementation adSubArrayOfUsermanager_Datastructure_Role

	- (id) init
	{
		if(self = [super init])
		{

		}
		return self;
	}

	+ (adSubArrayOfUsermanager_Datastructure_Role*) newWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (adSubArrayOfUsermanager_Datastructure_Role*)[[[adSubArrayOfUsermanager_Datastructure_Role alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"ArrayOfUsermanager_Datastructure_Role"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[adSubArrayOfUsermanager_Datastructure_Role class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		[super dealloc];
	}

@end
