/*
	adSubUsermanager_Datastructure_Roles.h
	The implementation of properties and methods for the adSubUsermanager_Datastructure_Roles object.
	Generated by SudzC.com
*/
#import "adSubUsermanager_Datastructure_Roles.h"

#import "adSubArrayOfUsermanager_Datastructure_Role.h"
@implementation adSubUsermanager_Datastructure_Roles
	@synthesize roles = _roles;

	- (id) init
	{
		if(self = [super init])
		{
			self.roles = nil; // [[adSubArrayOfUsermanager_Datastructure_Role alloc] init];

		}
		return self;
	}

	+ (adSubUsermanager_Datastructure_Roles*) newWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (adSubUsermanager_Datastructure_Roles*)[[[adSubUsermanager_Datastructure_Roles alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.roles = [[adSubArrayOfUsermanager_Datastructure_Role newWithNode: [Soap getNode: node withName: @"roles"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Usermanager_Datastructure_Roles"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.roles != nil) [s appendString: [self.roles serialize: @"roles"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[adSubUsermanager_Datastructure_Roles class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		if(self.roles != nil) { [self.roles release]; }
		[super dealloc];
	}

@end
