/*
	adSubUsermanager_Datastructure_Role.h
	The implementation of properties and methods for the adSubUsermanager_Datastructure_Role object.
	Generated by SudzC.com
*/
#import "adSubUsermanager_Datastructure_Role.h"

@implementation adSubUsermanager_Datastructure_Role
	@synthesize name = _name;
	@synthesize rank = _rank;

	- (id) init
	{
		if(self = [super init])
		{
			self.name = nil;

		}
		return self;
	}

	+ (adSubUsermanager_Datastructure_Role*) newWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (adSubUsermanager_Datastructure_Role*)[[[adSubUsermanager_Datastructure_Role alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.name = [Soap getNodeValue: node withName: @"name"];
			self.rank = [[Soap getNodeValue: node withName: @"rank"] intValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Usermanager_Datastructure_Role"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.name != nil) [s appendFormat: @"<name>%@</name>", [[self.name stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		[s appendFormat: @"<rank>%@</rank>", [NSString stringWithFormat: @"%i", self.rank]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[adSubUsermanager_Datastructure_Role class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		if(self.name != nil) { [self.name release]; }
		[super dealloc];
	}

@end
