/*
	adSubUsermanager_Soap_ManagementService.h
	The interface definition of classes and methods for the Usermanager_Soap_ManagementService web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "adSubArrayOfUsermanager_Datastructure_Role.h"
#import "adSubUsermanager_Datastructure_Roles.h"
#import "adSubUsermanager_Datastructure_Role.h"
#import "adSubUsermanager_Datastructure_LoginCredentials.h"

/* Interface for the service */
				
@interface adSubUsermanager_Soap_ManagementService : SoapService
		
	/* Returns adSubUsermanager_Datastructure_LoginCredentials*. isUserAllowed */
	- (SoapRequest*) isUserAllowed: (id <SoapDelegate>) handler username: (NSString*) username password: (NSString*) password idApp: (int) idApp hmacClient: (NSString*) hmacClient;
	- (SoapRequest*) isUserAllowed: (id) target action: (SEL) action username: (NSString*) username password: (NSString*) password idApp: (int) idApp hmacClient: (NSString*) hmacClient;

	/* Returns adSubUsermanager_Datastructure_Roles*.  */
	- (SoapRequest*) getRoles: (id <SoapDelegate>) handler;
	- (SoapRequest*) getRoles: (id) target action: (SEL) action;

	/* Returns int.  */
	- (SoapRequest*) getId: (id <SoapDelegate>) handler username: (NSString*) username;
	- (SoapRequest*) getId: (id) target action: (SEL) action username: (NSString*) username;

		
	+ (adSubUsermanager_Soap_ManagementService*) service;
	+ (adSubUsermanager_Soap_ManagementService*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	