/*
	adSubUsermanager_Datastructure_LoginCredentials.h
	The interface definition of properties and methods for the adSubUsermanager_Datastructure_LoginCredentials object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class adSubUsermanager_Datastructure_Roles;

@interface adSubUsermanager_Datastructure_LoginCredentials : SoapObject
{
	BOOL _accepted;
	NSString* _hmac;
	int _idUser;
	NSString* _message;
	adSubUsermanager_Datastructure_Roles* _roles;
	
}
		
	@property BOOL accepted;
	@property (retain, nonatomic) NSString* hmac;
	@property int idUser;
	@property (retain, nonatomic) NSString* message;
	@property (retain, nonatomic) adSubUsermanager_Datastructure_Roles* roles;

	+ (adSubUsermanager_Datastructure_LoginCredentials*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
