/*
	adSubUsermanager_Soap_ManagementService.m
	The implementation classes and methods for the Usermanager_Soap_ManagementService web service.
	Generated by SudzC.com
*/

#import "adSubUsermanager_Soap_ManagementService.h"
				
#import "Soap.h"
	
#import "adSubArrayOfUsermanager_Datastructure_Role.h"
#import "adSubUsermanager_Datastructure_Roles.h"
#import "adSubUsermanager_Datastructure_Role.h"
#import "adSubUsermanager_Datastructure_LoginCredentials.h"

/* Implementation of the service */
				
@implementation adSubUsermanager_Soap_ManagementService

	- (id) init
	{
		if(self = [super init])
		{
			self.serviceUrl = @"http://mathe.tugraz.at/%7Egeorg/Usermanager/public/soap";
			self.namespace = @"http://mathe.tugraz.at/%7Egeorg/Usermanager/public/soap";
			self.headers = nil;
			self.logging = NO;
		}
		return self;
	}
	
	- (id) initWithUsername: (NSString*) username andPassword: (NSString*) password {
		if(self = [super initWithUsername:username andPassword:password]) {
		}
		return self;
	}
	
	+ (adSubUsermanager_Soap_ManagementService*) service {
		return [adSubUsermanager_Soap_ManagementService serviceWithUsername:nil andPassword:nil];
	}
	
	+ (adSubUsermanager_Soap_ManagementService*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password {
		return [[[adSubUsermanager_Soap_ManagementService alloc] initWithUsername:username andPassword:password] autorelease];
	}

		
	/* Returns adSubUsermanager_Datastructure_LoginCredentials*. isUserAllowed */
	- (SoapRequest*) isUserAllowed: (id <SoapDelegate>) handler username: (NSString*) username password: (NSString*) password idApp: (int) idApp hmacClient: (NSString*) hmacClient
	{
		return [self isUserAllowed: handler action: nil username: username password: password idApp: idApp hmacClient: hmacClient];
	}

	- (SoapRequest*) isUserAllowed: (id) _target action: (SEL) _action username: (NSString*) username password: (NSString*) password idApp: (int) idApp hmacClient: (NSString*) hmacClient
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		[_params addObject: [[[SoapParameter alloc] initWithValue: username forName: @"username"] autorelease]];
		[_params addObject: [[[SoapParameter alloc] initWithValue: password forName: @"password"] autorelease]];
		[_params addObject: [[[SoapParameter alloc] initWithValue: [NSNumber numberWithInt: idApp] forName: @"idApp"] autorelease]];
		[_params addObject: [[[SoapParameter alloc] initWithValue: hmacClient forName: @"hmacClient"] autorelease]];
		NSString* _envelope = [Soap createEnvelope: @"isUserAllowed" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://mathe.tugraz.at/~georg/Usermanager/public/soap#isUserAllowed" postData: _envelope deserializeTo: [[adSubUsermanager_Datastructure_LoginCredentials alloc] autorelease]];
		[_request send];
		return _request;
	}

	/* Returns adSubUsermanager_Datastructure_Roles*.  */
	- (SoapRequest*) getRoles: (id <SoapDelegate>) handler
	{
		return [self getRoles: handler action: nil];
	}

	- (SoapRequest*) getRoles: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"getRoles" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://mathe.tugraz.at/~georg/Usermanager/public/soap#getRoles" postData: _envelope deserializeTo: [[adSubUsermanager_Datastructure_Roles alloc] autorelease]];
		[_request send];
		return _request;
	}

	/* Returns int.  */
	- (SoapRequest*) getId: (id <SoapDelegate>) handler username: (NSString*) username
	{
		return [self getId: handler action: nil username: username];
	}

	- (SoapRequest*) getId: (id) _target action: (SEL) _action username: (NSString*) username
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		[_params addObject: [[[SoapParameter alloc] initWithValue: username forName: @"username"] autorelease]];
		NSString* _envelope = [Soap createEnvelope: @"getId" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://mathe.tugraz.at/~georg/Usermanager/public/soap?wsdl#getId" postData: _envelope deserializeTo: @"int"];
		[_request send];
		return _request;
	}


@end
	