/*
	ws1x1ArrayOfUsermanager_Datastructure_Role.h
	The interface definition of properties and methods for the ws1x1ArrayOfUsermanager_Datastructure_Role object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface adSubArrayOfUsermanager_Datastructure_Role : SoapObject
{
	
}
		

	+ (adSubArrayOfUsermanager_Datastructure_Role*) newWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
