/*
	adSubUsermanager_Datastructure_LoginCredentials.h
	The implementation of properties and methods for the adSubUsermanager_Datastructure_LoginCredentials object.
	Generated by SudzC.com
*/
#import "adSubUsermanager_Datastructure_LoginCredentials.h"

#import "adSubUsermanager_Datastructure_Roles.h"
@implementation adSubUsermanager_Datastructure_LoginCredentials
	@synthesize accepted = _accepted;
	@synthesize hmac = _hmac;
	@synthesize idUser = _idUser;
	@synthesize message = _message;
	@synthesize roles = _roles;

	- (id) init
	{
		if(self = [super init])
		{
			self.hmac = nil;
			self.message = nil;
			self.roles = nil; // [[adSubUsermanager_Datastructure_Roles alloc] init];

		}
		return self;
	}

	+ (adSubUsermanager_Datastructure_LoginCredentials*) newWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (adSubUsermanager_Datastructure_LoginCredentials*)[[[adSubUsermanager_Datastructure_LoginCredentials alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.accepted = [[Soap getNodeValue: node withName: @"accepted"] boolValue];
			self.hmac = [Soap getNodeValue: node withName: @"hmac"];
			self.idUser = [[Soap getNodeValue: node withName: @"idUser"] intValue];
			self.message = [Soap getNodeValue: node withName: @"message"];
			self.roles = [[adSubUsermanager_Datastructure_Roles newWithNode: [Soap getNode: node withName: @"roles"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Usermanager_Datastructure_LoginCredentials"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		[s appendFormat: @"<accepted>%@</accepted>", (self.accepted)?@"true":@"false"];
		if (self.hmac != nil) [s appendFormat: @"<hmac>%@</hmac>", [[self.hmac stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		[s appendFormat: @"<idUser>%@</idUser>", [NSString stringWithFormat: @"%i", self.idUser]];
		if (self.message != nil) [s appendFormat: @"<message>%@</message>", [[self.message stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.roles != nil) [s appendString: [self.roles serialize: @"roles"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[adSubUsermanager_Datastructure_LoginCredentials class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		if(self.hmac != nil) { [self.hmac release]; }
		if(self.message != nil) { [self.message release]; }
		if(self.roles != nil) { [self.roles release]; }
		[super dealloc];
	}

@end
